### ISSUE TITLE
Warning and then Error for out of bounds issue

### ISSUE THREAD

**Issue by murphymadeleine21** [Katsevich-Lab/sceptre#176]
Hi,

I'm getting a warning message when I run `create_sceptre_object` and then an error in subsequent function calls including `assign_grnas` and `run_qc`:

> 1: In obtain_pointer_vector(i = dt$i, dim = n_responses) :
  subscript out of bounds (index 1377902 >= vector size 1377902)
2: In compute_nt_nonzero_matrix_and_n_ok_pairs_v3(j = response_matrix@j,  :
  subscript out of bounds (index 55532 >= vector size 55532)

It seems to be some form of out of bounds error but I cannot locate the issue within my datasets. Here's my sceptre object:

> An object of class sceptre_object.

Attributes of the data:
	• 16394 cells
	• 311 responses
	• High multiplicity-of-infection 
	• 33685 targeting gRNAs (distributed across 3750 targets) 
	• 0 non-targeting gRNAs 
	• 4 covariates (grna_n_nonzero, grna_n_umis, response_n_nonzero, response_n_umis)

Analysis status:
	✓ import_data()
	✓ set_analysis_parameters()
	✗ assign_grnas()
	✗ run_qc()
	✗ run_calibration_check()
	✗ run_power_check()
	✗ run_discovery_analysis()

Analysis parameters: 
	• Discovery pairs: data frame with 55532 pairs
	• Positive control pairs: not specified
	• Sidedness of test: both
	• N nonzero treatment cells threshold: not specified
	• N nonzero control cells threshold: not specified
	• Resampling mechanism: conditional resampling
	• gRNA integration strategy: union
	• Formula object: log(response_n_nonzero) + log(response_n_umis) + log(grna_n_nonzero + 1) + log(grna_n_umis + 1)

Im using R 4.1.2 and sceptre 0.9.0

**Comment by timothy-barry** [comment]
Hi Maddie,

A couple other users reported a similar issue. I believe that we fixed this issue as of the current version of the package. Would it be possible for you to redownload `sceptre`, try again, and report back? :)

Tim

**Comment by murphymadeleine21** [comment]
Hi Tim,

Thanks for the quick reply! I just updated to `sceptre 0.10.2` and I'm still getting the issue.

Maddie

**Comment by timothy-barry** [comment]
Hm, OK. Is the error preventing you from running your code? And are you using your own dataset? Finally, I wonder if you might be able to provide me with a minimal reproducible example? Alternately, if you were able to send me your `sceptre_object`, I probably could debug the issue pretty quickly.

**Comment by ekatsevi** [comment]
Hi @murphymadeleine21, we're trying to track down this out-of-bounds error, and it would be really helpful for us to have a dataset to reproduce the issue. Would you be able to share with us the `sceptre_object` and the code that gives the error? We would keep the data confidential and delete it upon resolution of the bug. If you were willing, you can send the data (or a link to it) to ekatsevi@wharton.upenn.edu. Thank you!

**Comment by ekatsevi** [comment]
Thank you!

**Comment by ekatsevi** [comment]
Hi @murphymadeleine21 — we revisited this report and confirmed that the underlying issue was fixed in [commit 76f3432](https://github.com/Katsevich-Lab/sceptre/commit/76f343256494389ca463edcda94f7550f7a7dec1), which was included in `sceptre` v0.10.2.

We recognize that you still saw the warnings after updating; it is possible that the previous compiled version remained loaded in the existing R session.

We are closing this as fixed. If the problem recurs with the current version in a fresh R session, please reopen the issue with `sessionInfo()` and the complete error message. Thanks again for reporting it.
